/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import configDB.crud;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author ASUS
 */
public class FrameBarangTemuan extends javax.swing.JFrame {
private crud objekKu;
    /**
     * Creates new form FrameBarangTemuan
     */
    public FrameBarangTemuan() {
        initComponents();
        this.setLocationRelativeTo(null);
        objekKu = new crud();
        
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });
        tabelBarangTemuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBarangTemuanMouseClicked(evt);
            }
        });
       
        isiComboBox();
        tampilkanDataBarangTemuan("");
      
    }

private void isiComboBox() {
        // 1. Mengisi cmbKondisi (Data Statis/ENUM Kondisi Barang)
        cmbKondisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
            "Baik", "Kurang Baik", "Rusak"
        }));
        
        // 2. Mengisi cmbKategori (Data Dinamis dari Database)
        tampilkanDataKategori(); 
    }

    private void tampilkanDataKategori() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        String query = "SELECT nama_kategori FROM KATEGORI_BARANG ORDER BY nama_kategori";
        ResultSet rs = objekKu.getData(query);
        
        try {
            model.addElement("-- Pilih Kategori --");
            while (rs.next()) {
                model.addElement(rs.getString("nama_kategori"));
            }
            cmbKategori.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data Kategori dari DB: " + e.getMessage());
        }
    }
    
    private String getIDKategori(String namaKategori) {
        if (namaKategori.equals("-- Pilih Kategori --")) return "1"; 
        
        String idKat = "1"; 
        try {
            String query = "SELECT id_kategori FROM KATEGORI_BARANG WHERE nama_kategori = '" + namaKategori + "'";
            ResultSet rs = objekKu.getData(query);
            if (rs.next()) {
                idKat = rs.getString("id_kategori");
            }
        } catch (SQLException e) {
            System.err.println("Error get ID Kategori: " + e.getMessage());
        }
        return idKat;
    }
    private void tampilkanDataBarangTemuan(String keyword) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID BT");
        model.addColumn("Nama Barang");
        model.addColumn("Tgl Masuk");
        model.addColumn("Jumlah");
        model.addColumn("Kondisi");
        
        try {
            String query = "SELECT id_barang_temuan, nama_barang, tanggal_masuk, jumlah_barang, kondisi_barang " +
                           "FROM BARANG_TEMUAN " +
                           "WHERE nama_barang LIKE '%" + keyword + "%' OR " +
                           "id_barang_temuan LIKE '%" + keyword + "%' " +
                           "ORDER BY id_barang_temuan DESC";
            
            ResultSet rs = objekKu.getData(query);
            
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_barang_temuan"),
                    rs.getString("nama_barang"),
                    rs.getString("tanggal_masuk"),
                    rs.getInt("jumlah_barang"),
                    rs.getString("kondisi_barang")
                });
            }
            tabelBarangTemuan.setModel(model); 
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error saat memuat data Barang Temuan: " + e.getMessage());
        }
    }
    private void clearFields() {
        // Asumsi: Variabel input telah dideklarasikan
        txtIDBarangTemuan.setText("");
        txtNamaBarang.setText("");
        txtTglMasuk.setText("");
        txtJumlah.setText("");
        txtSatuan.setText("");
        txtKeterangan.setText("");
        cmbKondisi.setSelectedIndex(0);
        cmbKategori.setSelectedIndex(0);
        tabelBarangTemuan.clearSelection();
        // Tambahkan logika refresh tombol jika menggunakan JTable
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIDBarangTemuan = new javax.swing.JTextField();
        txtNamaBarang = new javax.swing.JTextField();
        txtTglMasuk = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        txtSatuan = new javax.swing.JTextField();
        cmbKondisi = new javax.swing.JComboBox<>();
        cmbKategori = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKeterangan = new javax.swing.JTextArea();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelBarangTemuan = new javax.swing.JTable();
        btnCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FORM BARANG TEMUAN");

        jLabel2.setText("ID BARANG TEMUAN");

        jLabel3.setText("NAMA BARANG");

        jLabel4.setText("TANGGAL MASUK");

        jLabel5.setText("JUMLAH BARANG");

        jLabel6.setText("SATUAN");

        jLabel7.setText("KONDISI BARANG");

        jLabel8.setText("KETERANGAN");

        jLabel9.setText("KATEGORI");

        cmbKondisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baik", "Kurang Baik", "Rusak" }));

        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kendaraan Roda Empat", "Kendaraan Roda Dua", "Telephone / Gadget", "Lainnya" }));

        txtKeterangan.setColumns(20);
        txtKeterangan.setRows(5);
        jScrollPane1.setViewportView(txtKeterangan);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnClear.setText("Bersihkan");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        tabelBarangTemuan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelBarangTemuan);

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIDBarangTemuan)
                                    .addComponent(txtNamaBarang)
                                    .addComponent(txtTglMasuk)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cmbKondisi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtJumlah)
                                                .addComponent(txtSatuan)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 8, Short.MAX_VALUE)))))))
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addGap(18, 18, 18)
                                .addComponent(btnUbah)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCetak))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                            .addComponent(txtCari, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtIDBarangTemuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTglMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnClear)
                    .addComponent(btnCetak))
                .addGap(35, 35, 35)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {                                    
        String keyword = txtCari.getText();
        tampilkanDataBarangTemuan(keyword);
    }
    private void tabelBarangTemuanMouseClicked(java.awt.event.MouseEvent evt) {                                           
        int baris = tabelBarangTemuan.getSelectedRow();
        if (baris != -1) {
            // Ambil data dari tabel (0:ID BT, 1:Nama, 2:Tgl Masuk, 3:Jumlah, 4:Kondisi)
            String id = tabelBarangTemuan.getValueAt(baris, 0).toString();
            String nama = tabelBarangTemuan.getValueAt(baris, 1).toString();
            String tglMasuk = tabelBarangTemuan.getValueAt(baris, 2).toString();
            String jumlah = tabelBarangTemuan.getValueAt(baris, 3).toString();
            String kondisi = tabelBarangTemuan.getValueAt(baris, 4).toString();
            
            // Isi Field Input
            txtIDBarangTemuan.setText(id);
            txtNamaBarang.setText(nama);
            txtTglMasuk.setText(tglMasuk);
            txtJumlah.setText(jumlah);
            // Keterangan dan Satuan harus diambil via query tambahan jika tidak ada di tabel view
            
            cmbKondisi.setSelectedItem(kondisi);
            
            // Atur status tombol
            btnTambah.setEnabled(false);
            btnUbah.setEnabled(true);
            btnHapus.setEnabled(true);
        }
    }
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        try {
            String idBT = txtIDBarangTemuan.getText();
            String nama = txtNamaBarang.getText();
            String tglMasuk = txtTglMasuk.getText(); 
            int jumlah = Integer.parseInt(txtJumlah.getText());
            String satuan = txtSatuan.getText();
            String kondisi = cmbKondisi.getSelectedItem().toString(); 
            String ket = txtKeterangan.getText(); 
            
            String idUser = "1"; // ID User yang sedang login
            String namaKategori = cmbKategori.getSelectedItem().toString(); 
            String idKat = getIDKategori(namaKategori); 
            
            if (idBT.isEmpty() || nama.isEmpty() || tglMasuk.isEmpty()) {
                JOptionPane.showMessageDialog(this, "ID, Nama, dan Tanggal Masuk tidak boleh kosong!");
                return;
            }
            
            // Urutan parameter di crud.simpanBarangTemuan: idBT, nama, tglMasuk, jumlah, satuan, kondisi, ket, idUser, idKat
            objekKu.simpanBarangTemuan(idBT, nama, tglMasuk, jumlah, satuan, kondisi, ket, idUser, idKat);
            JOptionPane.showMessageDialog(this, "Data Barang Temuan berhasil disimpan!");
            clearFields();
            tampilkanDataBarangTemuan("");
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input Jumlah tidak valid (harus angka): " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saat menambah data: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        try {
            String idBT = txtIDBarangTemuan.getText();
            String nama = txtNamaBarang.getText();
            String tglMasuk = txtTglMasuk.getText();
            int jumlah = Integer.parseInt(txtJumlah.getText());
            String satuan = txtSatuan.getText();
            String kondisi = cmbKondisi.getSelectedItem().toString();
            String ket = txtKeterangan.getText();
            
            String idUser = "1"; 
            String namaKategori = cmbKategori.getSelectedItem().toString(); 
            String idKat = getIDKategori(namaKategori); 
            
            if (idBT.isEmpty()) {
                JOptionPane.showMessageDialog(this, "ID Barang Temuan harus diisi untuk mengubah data!");
                return;
            }
            
            // Urutan parameter di crud.ubahBarangTemuan: idBT, nama, tglMasuk, jumlah, satuan, kondisi, ket, idUser, idKat
            objekKu.ubahBarangTemuan(idBT, nama, tglMasuk, jumlah, satuan, kondisi, ket, idUser, idKat);
            JOptionPane.showMessageDialog(this, "Data Barang Temuan berhasil diubah!");
            clearFields();
            tampilkanDataBarangTemuan("");
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input Jumlah tidak valid (harus angka): " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saat mengubah data: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            String idBT = txtIDBarangTemuan.getText();
            if (idBT.isEmpty()) {
                JOptionPane.showMessageDialog(this, "ID Barang Temuan harus diisi untuk menghapus data!");
                return;
            }
            
            int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin hapus Barang Temuan ID " + idBT + "?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
            
            if (konfirmasi == JOptionPane.YES_OPTION) {
                 objekKu.hapusBarangTemuan(idBT);
                 JOptionPane.showMessageDialog(this, "Data Barang Temuan berhasil dihapus!");
                 clearFields();
                 tampilkanDataBarangTemuan("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saat menghapus data: " + e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        objekKu.tampilLaporan("laporanBarangTemuan");
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameBarangTemuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameBarangTemuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameBarangTemuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameBarangTemuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameBarangTemuan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JComboBox<String> cmbKondisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelBarangTemuan;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtIDBarangTemuan;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextArea txtKeterangan;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtSatuan;
    private javax.swing.JTextField txtTglMasuk;
    // End of variables declaration//GEN-END:variables
}
