/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import configDB.crud;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class FrameLogAktivitas extends javax.swing.JFrame {
private crud objekKu;
private int selectedIdLog = -1;
private javax.swing.JTable tabelLog;
    /**
     * Creates new form FrameLogAktivitas
     */
    public FrameLogAktivitas() {
        initComponents();
    this.setLocationRelativeTo(null);
    objekKu = new crud();
    tabelLog = jTable1; 
    
    // Sekarang, tampilkanDataLog() aman untuk dipanggil karena tabelLog sudah diinisialisasi
    tampilkanDataLog();
    btnHapusLogTerpilih.setEnabled(false);
    }
private void tampilkanDataLog() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Log");
        model.addColumn("ID User");
        model.addColumn("Waktu Aksi");
        model.addColumn("Jenis Aksi");
        model.addColumn("Deskripsi");
        
        try {
            // Query JOIN untuk menampilkan Username/Nama Pegawai (jika diperlukan)
            String query = "SELECT l.id_log, l.id_user, l.waktu_aksi, l.jenis_aksi, l.deskripsi FROM LOG_AKTIVITAS l ORDER BY l.waktu_aksi DESC";
            ResultSet rs = objekKu.getData(query);
            
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_log"),
                    rs.getInt("id_user"),
                    rs.getTimestamp("waktu_aksi"),
                    rs.getString("jenis_aksi"),
                    rs.getString("deskripsi")
                });
            }
            tabelLog.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error saat memuat data Log: " + e.getMessage());
        }
    }
private void clearSelection() {
        selectedIdLog = -1;
        btnHapusLogTerpilih.setEnabled(false);
        tabelLog.clearSelection();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnHapusLogTerpilih = new javax.swing.JButton();
        btnClearForm = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("LOG AKTIVITAS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnHapusLogTerpilih.setText("Hapus");
        btnHapusLogTerpilih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusLogTerpilihMouseClicked(evt);
            }
        });
        btnHapusLogTerpilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusLogTerpilihActionPerformed(evt);
            }
        });

        btnClearForm.setText("Bersihkan");
        btnClearForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFormActionPerformed(evt);
            }
        });

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapusLogTerpilih)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClearForm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCetak)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(btnHapusLogTerpilih)
                    .addComponent(btnClearForm)
                    .addComponent(btnCetak))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearFormActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
       tampilkanDataLog();
        clearSelection();
    
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnHapusLogTerpilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusLogTerpilihActionPerformed
      if (selectedIdLog == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris log yang akan dihapus.");
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin hapus Log ID " + selectedIdLog + "?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
            
        if (konfirmasi == JOptionPane.YES_OPTION) {
            // Memanggil method dari class crud
            // Asumsi: crud.hapusLogAktivitas(int id) mengembalikan boolean
            boolean result = objekKu.hapusLogAktivitas(selectedIdLog);
            
            if (result) {
                JOptionPane.showMessageDialog(this, "Log berhasil dihapus!");
                tampilkanDataLog();
                clearSelection();
            } else {
                 JOptionPane.showMessageDialog(this, "Gagal menghapus Log.");
            }
        }
    }//GEN-LAST:event_btnHapusLogTerpilihActionPerformed

    private void btnHapusLogTerpilihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusLogTerpilihMouseClicked
        int baris = tabelLog.getSelectedRow();
        if (baris != -1) {
            // ID Log ada di kolom 0 (sesuai DefaultTableModel)
            selectedIdLog = (int) tabelLog.getValueAt(baris, 0); 
            btnHapusLogTerpilih.setEnabled(true);
        }
    }//GEN-LAST:event_btnHapusLogTerpilihMouseClicked

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        objekKu.tampilLaporan("laporanLogAktivitas");
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameLogAktivitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameLogAktivitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameLogAktivitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameLogAktivitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameLogAktivitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnClearForm;
    private javax.swing.JButton btnHapusLogTerpilih;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
