/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class FrameDashboard extends javax.swing.JFrame {

    /**
     * Creates new form FrameDashboard
     */
    public FrameDashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnKelolaPengguna = new javax.swing.JButton();
        btnKelolaKategori = new javax.swing.JButton();
        btnBarangBukti = new javax.swing.JButton();
        btnBarangTemuan = new javax.swing.JButton();
        btnLogAktivitas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MENU UTAMA PENGELOLAAN BARANG");

        btnKelolaPengguna.setText("1. KELOLA PENGGUNA");
        btnKelolaPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPenggunaActionPerformed(evt);
            }
        });

        btnKelolaKategori.setText("2. KELOLA KATEGORI");
        btnKelolaKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaKategoriActionPerformed(evt);
            }
        });

        btnBarangBukti.setText("3. INPUT BARANG BUKTI");
        btnBarangBukti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarangBuktiActionPerformed(evt);
            }
        });

        btnBarangTemuan.setText("4. INPUT BARANG TEMUAN");
        btnBarangTemuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarangTemuanActionPerformed(evt);
            }
        });

        btnLogAktivitas.setText("5. LIHAT LOG AKTIVITAS");
        btnLogAktivitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogAktivitasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKelolaPengguna, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKelolaKategori, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBarangBukti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBarangTemuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogAktivitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnKelolaPengguna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKelolaKategori)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBarangBukti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBarangTemuan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogAktivitas)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKelolaPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPenggunaActionPerformed
        new FramePengguna().setVisible(true);
    }//GEN-LAST:event_btnKelolaPenggunaActionPerformed

    private void btnBarangTemuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangTemuanActionPerformed
        new FrameBarangTemuan().setVisible(true);
    }//GEN-LAST:event_btnBarangTemuanActionPerformed

    private void btnKelolaKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaKategoriActionPerformed
       new FrameKategori().setVisible(true);
    }//GEN-LAST:event_btnKelolaKategoriActionPerformed

    private void btnBarangBuktiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangBuktiActionPerformed
        new frameBarangBukti().setVisible(true);
    }//GEN-LAST:event_btnBarangBuktiActionPerformed

    private void btnLogAktivitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogAktivitasActionPerformed
        new FrameLogAktivitas().setVisible(true);
    }//GEN-LAST:event_btnLogAktivitasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBarangBukti;
    private javax.swing.JButton btnBarangTemuan;
    private javax.swing.JButton btnKelolaKategori;
    private javax.swing.JButton btnKelolaPengguna;
    private javax.swing.JButton btnLogAktivitas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
